Repository sacloud/terraform-provider-sakuracloud, pull requests merged in 2021-03, with the labels that each got.

#799 libsacloud v2.14.0
  .github/workflows/release.yaml
  .github/workflows/tests.yaml
  GNUmakefile
  go.mod
  go.sum
  sakuracloud/resource_sakuracloud_cdrom.go
  sakuracloud/structure_icon.go
  tools/tfdocgen/provider.go
  vendor/github.com/sacloud/libsacloud/v2/Makefile
  vendor/github.com/sacloud/libsacloud/v2/go.mod
  vendor/github.com/sacloud/libsacloud/v2/go.sum
  vendor/github.com/sacloud/libsacloud/v2/sacloud/client.go
  vendor/github.com/sacloud/libsacloud/v2/sacloud/fake/json_file_store.go
  vendor/github.com/sacloud/libsacloud/v2/sacloud/profile/profile.go
  vendor/github.com/sacloud/libsacloud/v2/version.go
  vendor/modules.txt
Labels: area/datasources, area/resources, v2

#800 darwin/arm64
  .goreleaser.yml
Labels: v2

#802 sakuracloud_sim: Sentitive:true
  sakuracloud/resource_sakuracloud_sim.go
Labels: area/resources, breaking-change, v2

#805 sakuracloud_server: ssh_keys
  examples/website/r/server/server.tf
  sakuracloud/resource_sakuracloud_server.go
  sakuracloud/resource_sakuracloud_server_test.go
  sakuracloud/structure_server.go
  website/docs/r/server.md
Labels: area/resources, v2

#806 libsacloud v2.14.1 - added internet plans
  go.mod
  go.sum
  vendor/github.com/sacloud/libsacloud/v2/sacloud/types/internet_constants.go
  vendor/modules.txt
  website/docs/r/internet.md
Labels: area/resources, v2

#809 Added some rules for tfproviderlint
  GNUmakefile
  sakuracloud/helpers_test.go
  sakuracloud/resource_sakuracloud_mobile_gateway.go
Labels: area/development, v2

#811 Fix packet_filter examples
  examples/website/r/packet_filter/packet_filter.tf
  examples/website/r/packet_filter_rules/packet_filter_rules.tf
  website/docs/r/packet_filter.md
  website/docs/r/packet_filter_rules.md
Labels: area/docs, v2

#812 Fixed parameter handling for server plan change operation
  go.mod
  go.sum
  sakuracloud/resource_sakuracloud_server_test.go
  vendor/github.com/sacloud/libsacloud/v2/helper/builder/server/builder.go
  vendor/github.com/sacloud/libsacloud/v2/sacloud/fake/ops_server.go
  vendor/github.com/sacloud/libsacloud/v2/sacloud/naked/esme.go
  vendor/github.com/sacloud/libsacloud/v2/sacloud/zz_envelopes.go
  vendor/github.com/sacloud/libsacloud/v2/sacloud/zz_models.go
  vendor/github.com/sacloud/libsacloud/v2/version.go
  vendor/modules.txt
Labels: area/resources, v2
